#!/usr/bin/env python3
"""Combine a domain's per-chapter LaTeX notes into a single PDF.

Reads every chapter's notes/notes.tex, extracts the text between the APORE
body markers, concatenates the bodies under one preamble, and runs latexmk.

See docs/superpowers/specs/2026-09-19-latex-notes-design.md
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

BODY_START = "% >>> APORE BODY START"
BODY_END = "% <<< APORE BODY END"

EXIT_OK = 0
EXIT_INPUT = 1
EXIT_NO_LATEXMK = 2
EXIT_BUILD_FAILED = 3

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_DIR = REPO_ROOT / "shared" / "_templates" / "notes"


class InputError(Exception):
    """Unusable input: bad selection, missing markers, nothing to build."""


def parse_chapter_selection(spec):
    """Expand a selection string such as "1-3,7" into {1, 2, 3, 7}."""
    numbers = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            low, _, high = part.partition("-")
            try:
                low_n, high_n = int(low), int(high)
            except ValueError:
                raise InputError("invalid chapter range: %r" % part)
            if low_n > high_n:
                raise InputError("reversed chapter range: %r" % part)
            numbers.update(range(low_n, high_n + 1))
        else:
            try:
                numbers.add(int(part))
            except ValueError:
                raise InputError("invalid chapter number: %r" % part)
    if not numbers:
        raise InputError("empty chapter selection: %r" % spec)
    return numbers


def chapter_number(folder_name):
    """Leading digits of a chapter folder name, or None."""
    match = re.match(r"^(\d+)", folder_name)
    return int(match.group(1)) if match else None


def discover_chapters(domain_dir):
    """All numbered chapter folders in a domain, ordered by number."""
    chapters_dir = domain_dir / "chapters"
    if not chapters_dir.is_dir():
        raise InputError("no chapters/ folder in %s" % domain_dir)
    found = []
    for child in sorted(chapters_dir.iterdir()):
        if not child.is_dir():
            continue
        number = chapter_number(child.name)
        if number is not None:
            found.append((number, child))
    found.sort(key=lambda pair: pair[0])
    return found


def select_chapters(chapters, wanted):
    """Filter chapters to those with notes. Returns (selected, warnings)."""
    selected = []
    warnings = []
    for number, chapter_dir in chapters:
        if wanted is not None and number not in wanted:
            continue
        notes_tex = chapter_dir / "notes" / "notes.tex"
        if not notes_tex.is_file():
            warnings.append(
                "chapter %02d (%s): no notes/notes.tex, skipped"
                % (number, chapter_dir.name)
            )
            continue
        selected.append((number, notes_tex))
    if wanted is not None:
        present = {number for number, _ in chapters}
        for number in sorted(wanted - present):
            warnings.append("chapter %02d: not found in this domain" % number)
    return selected, warnings


def extract_body(tex_path):
    """Text between the body markers.

    A missing marker is fatal rather than a skip: silently dropping a chapter
    from a study book is worse than refusing to build it.
    """
    text = tex_path.read_text(encoding="utf-8")
    start = text.find(BODY_START)
    end = text.find(BODY_END)
    if start == -1:
        raise InputError("%s: missing marker %r" % (tex_path, BODY_START))
    if end == -1:
        raise InputError("%s: missing marker %r" % (tex_path, BODY_END))
    if end < start:
        raise InputError("%s: end marker precedes start marker" % tex_path)
    return text[start + len(BODY_START):end].strip("\n")


def domain_display_name(domain_dir):
    """First '# ' heading of DOMAIN.md, falling back to the folder name."""
    domain_md = domain_dir / "DOMAIN.md"
    if domain_md.is_file():
        for line in domain_md.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    return domain_dir.name


def output_stem(numbers, is_subset):
    """Base filename. Ranges are expanded, so a suffix never fakes a range."""
    if not is_subset:
        return "full-notes"
    return "full-notes-ch" + "-".join("%02d" % n for n in numbers)


def build_master_tex(domain_name, bodies, today):
    """Assemble the combined document source."""
    header = "\n".join([
        "% Generated by shared/scripts/build_notes.py. Do not edit by hand.",
        "% Edit each chapter's notes/notes.tex instead, then rebuild.",
        "\\documentclass[11pt]{article}",
        "\\usepackage[combined,toc]{apore-notes}",
        "",
        "\\notesmeta{%s}{Full Notes}{%s}" % (domain_name, today),
        "",
        "\\begin{document}",
        "\\makenotestitle",
        "",
    ])
    return header + "\n" + "\n\n".join(bodies) + "\n\n\\end{document}\n"


def copy_assets(out_dir):
    """Refresh the style package and the README from the templates.

    Both are overwritten every run. The README itself states that edits here
    are lost on the next build, so keeping a stale copy would make the folder
    contradict its own instructions.
    """
    sty_src = TEMPLATE_DIR / "apore-notes.sty"
    if not sty_src.is_file():
        raise InputError("missing template: %s" % sty_src)
    shutil.copyfile(sty_src, out_dir / "apore-notes.sty")
    readme_src = TEMPLATE_DIR / "full-notes-README.md"
    if readme_src.is_file():
        shutil.copyfile(readme_src, out_dir / "README.md")


def run_latexmk(tex_name, cwd):
    """Build the PDF. Returns an exit code."""
    if shutil.which("latexmk") is None:
        return EXIT_NO_LATEXMK
    result = subprocess.run(
        ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", tex_name],
        cwd=str(cwd),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        tail = (result.stdout + result.stderr).splitlines()[-20:]
        for line in tail:
            print(line, file=sys.stderr)
        return EXIT_BUILD_FAILED
    return EXIT_OK


def resolve_domain(name):
    """Accept a domain folder name or a path to one."""
    candidate = REPO_ROOT / name
    if candidate.is_dir():
        return candidate.resolve()
    direct = Path(name)
    if direct.is_dir():
        return direct.resolve()
    raise InputError("unknown domain: %s" % name)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Combine a domain's chapter notes into one PDF."
    )
    parser.add_argument("domain", help="domain folder name, e.g. material204")
    parser.add_argument(
        "--chapters", help="chapter selection, e.g. 1-3 or 1,3,5"
    )
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="write the .tex but do not run latexmk",
    )
    args = parser.parse_args(argv)

    try:
        domain_dir = resolve_domain(args.domain)
        wanted = parse_chapter_selection(args.chapters) if args.chapters else None
        chapters = discover_chapters(domain_dir)
        selected, warnings = select_chapters(chapters, wanted)
        for warning in warnings:
            print("warning: %s" % warning, file=sys.stderr)
        if not selected:
            raise InputError("no chapters with notes/notes.tex were selected")
        bodies = [extract_body(path) for _, path in selected]
        out_dir = domain_dir / "full-notes"
        out_dir.mkdir(parents=True, exist_ok=True)
        copy_assets(out_dir)
    except InputError as error:
        print("error: %s" % error, file=sys.stderr)
        return EXIT_INPUT

    stem = output_stem([n for n, _ in selected], wanted is not None)
    tex_path = out_dir / (stem + ".tex")
    tex_path.write_text(
        build_master_tex(
            domain_display_name(domain_dir), bodies, date.today().isoformat()
        ),
        encoding="utf-8",
    )
    print("wrote %s (%d chapters)" % (tex_path, len(selected)))

    if args.no_build:
        return EXIT_OK

    status = run_latexmk(tex_path.name, out_dir)
    if status == EXIT_NO_LATEXMK:
        print(
            "error: latexmk not found on PATH. Install MiKTeX "
            "(Windows: winget install MiKTeX.MiKTeX) or MacTeX/BasicTeX (macOS).",
            file=sys.stderr,
        )
    elif status == EXIT_BUILD_FAILED:
        print("error: latexmk failed for %s" % tex_path.name, file=sys.stderr)
    else:
        print("built %s" % (out_dir / (stem + ".pdf")))
    return status


if __name__ == "__main__":
    sys.exit(main())
